services:
  frontend:
    image: $${{ vars.USERNAME }}/shri-frontend:latest
    container_name: shri-frontend
    ports:
      - "80:80"
    depends_on:
      - backend
    restart: unless-stopped

  backend:
    image: $${{ vars.PASSWORD }}/shri-backend:latest
    container_name: shri-backend
    ports:
      - "5000:5000"
    restart: unless-stopped
