name: compose

inputs:
  name:
    description: yogesh
    type: string
    required: true
    default: yogesh
  language:
    description: the greeting language
    default: 'en'
    type: string
    required: true

outputs:
  greeted:
    value: ${{ steps.print.outputs.greeted }}


runs:
  using: composite

  steps:
      
    - name: greeting
      shell: bash
      run: echo "hello! ${{ inputs.name }}"

    - name: date
      shell: bash
      run: echo "$(date)"

    - name: runner
      shell: bash
      run: echo "${{ runner.os }}"
      
    - id: print
      shell: bash
      run: echo "greeted_status=true" >> $GITHUB_OUTPUT




