name: caller

on:
  push:
    branches: [ "main" ]

jobs:
  token:
    uses: ./.github/workflows/reusable-build.yml

    with:
      app_name: "my-web-app"
      environment: "production"
    secrets:
      docker_token: ${{ secrets.DOCKER_TOKEN }}


  second:
    runs-on: ubuntu-latest
    needs: token

    steps:
      - name: use output from job1
        env:
          my_output_1: ${{ needs.rreuse.outputs.my_output }}

        run: echo "$my_output_1"
