name: deploy-after-test

on:
  workflow_run:
    workflows: [ "run tests" ]
    types: [ completed ]


jobs:
  deploy:
    runs-on: ubuntu-latest
    if: ${{ github.event.workflow_run.conclusion == 'success' }}
    steps:
      - name: code checkout
        uses: actions/checkout@v4
      
      - name: deploying
        run: echo "Deploying...."

  
