name: greeter


on:
  push:
    branches: [ "main" ]


jobs:
  second:
    runs-on: ubuntu-latest

    steps:
      - name: code-checkout
        uses: actions/checkout@v4

      - id: greeting
        uses: ./.github/actions/setup-and-greet
        with:
          name: "yogesh"

      - name: Verify Greeting Output
        run: echo "Was the user greeted? ${{ steps.greeting.outputs.greeted }}"

