name: health_check
on:
  push:
    branches: [ "main" ]

jobs:
  view_health:
    runs-on: ubuntu-latest

    steps:
      - name: code checkout
        uses: actions/checkout@v4

      - name: script execution
        run: ./healthcheck.sh
