name: hello
on:
  push:
    branches: [ "main" ]

jobs:
  greet:
    runs-on: ubuntu:latest

  steps:
    - name: code checkout
      uses: "actions/checkout@v4"

    - name: print hello
      uses: echo "Hello from GitHub Actions!"
