name: checking

on:
  push:
    branches: [ "main" ]

jobs:
  new:
   strategy:
    matrix:
      version: [ 10,12,14 ]
      os: [ ubuntu-latest ]

   runs-on: ${{ matrix.os }}

   steps:
      - name: os
        run : echo "cat /etc/os-release"
