name: pull-request

on:
  pull:
    branches: [ "main" ]

jobs:
  print:
    runs-on: ubuntu-latest

    steps:
      - name: code checkout
        uses: "actions/checkout@v4"

      - name: prints branch confirmation
        env:
          Branch_name: ${{ github.ref_name }}

        run: echo "PR check running for branch: $Branch_name"
