name: pull-request

on:
  pull_request:
    branches: [ "main" ]
    types: [ "opened" ]

jobs:
  print:
    runs-on: ubuntu-latest

    steps:
      - name: code checkout
        uses: "actions/checkout@v4"

      - name: prints branch confirmation
        run: echo "PR check running for branch: {{ github.head_ref }}"
