name: reuse

on:
  workflow_call:
    inputs:
      app_name:
        description: "new-app"
        type: string
        required: true

      environment:
        type: string
        required: true
        default: staging

    secrets:
      docker_token:
        required: true

    outputs:
      my-outputs: ${{ jobs.rreuse.outputs.my_job_output }}

jobs:
  rreuse:
    runs-on: ubuntu-latest

    outputs:
      my_job_output: ${{ steps.version.outputs.version }}

    steps:
      - name: code checkout
        uses: actions/checkout@v4


      - id: version
        run: |
          SHORT_SHA=$(echo "${{ github.sha }}" | cut -c1-7)
          echo "version=v1.0-${SHORT_SHA}" >> $GITHUB_OUTPUT

      - name: prints
        run: echo "Building $app_name for $environment"


      - name: Check docker token status
        run: |
          if [ -n "${{ secrets.docker_token }}" ];then 

            echo "Docker token is set: true"

          else 
            echo "Docker token is set: false"

          fi


