name: sch_task

on:
  schedule:
    - cron: '40 4 * * *'
    - cron: '0 */6 * * *'


jobs:
  to_check:
    runs-on: ubuntu-latest

    steps:
      - name: which trigger
        run: echo "${{ github.event.schedule }}"

      - name: curl
        run: curl https://www.google.com/webhp?hl=en&ictx=0&sa=X&ved=0ahUKEwiDvILd0LCVAxUHzTgGHfmuAN8QPAgH
