---
name: scheduled
on:
  schedule:
    - cron: "06 9 * * *"
jobs:
  new:
    runs-on: ubuntu-latest
    steps:
     - name: code checkout
       uses: "actions/checkout@v4"


     - name: success
       run: echo "Succesfull."
