name: self

on:
  push:
    branches: [ "main" ]

jobs:
  self_os:
    runs-on: [ self-hosted, my-linux-runner ]

    steps:
      - name: host
        run: hostname

      - name: working dir
        run: pwd

      - name: new-file
        run: mkdir created-via-selfhosted
