name: run tests

on:
  push:
    branches: [ "main" ]

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
      - name: code checkout
        uses: actions/checkout@v4

      - name: run test
        run: |
          echo "running tests..."
          echo "All tests cleared"
