name: variable

on:
  push:
    branches: [ "main" ]

env:
  APP_NAME: myapp

jobs:
  variables_list:
    runs-on: ubuntu-latest
    env:
      ENVIRONMENT: staging


    steps:
      - name: print version
        run: echo "$VERSION"

      - name: print app name
        run: echo "$APP_NAME"

      - name: print environment
        run: echo "$ENVIRONMENT"

        env:
          VERSION: 1.0.0
